project:
  id: 1a4b94b3-e6cf-4367-a0b0-ad01e5ef310e
  name: 'DS Capstone Project: Signal Sigma'
  description: >-
    Financial forecasting pipeline using Temporal Fusion Transformer with engineered features, probabilistic predictions, and an interactive Streamlit dashboard
  authors:
    - name: Julia Loeschel
      github: https://github.com/julialoeschel
    - name: Paya Moghtanem
      github: https://github.com/payamoghtanem
    - name: Benas 67
      github: https://github.com/Benas67
    - name: Kvn Dtrx
      mail: kvn.dtrx+git@protonmail.ch
      github: https://github.com/kvn-dtrx
  license:
    type: MIT
    year: 2025
  github-fork: https://github.com/kvn-dtrx/ds-capstone-project_signal-sigma
forges:
  github:
    url: https://github.com/julialoeschel/capstone-SignalSigma
    visibility: public
